version: '3'

services:
  web_static:
    build: .
    restart: always
    ports: 
      - "8080:80"
    volumes:
      - .:/usr/share/nginx/html
      - ./pretest.conf:/etc/nginx/conf.d/pretest.conf
